### ISSUE TITLE
"Wrong fb secret!" - How to configure the Facebook Connector correctly? - Python 3 only

### ISSUE THREAD

**Issue by bastiW** [RasaHQ/rasa_core#161]
**Rasa Core version**: rasa-core (0.8.0a4, /root/rasa_core) including pull request #160 

**Python version**: Python 3.6.3 |Anaconda, Inc.

**Operating system** : Ubuntu 16.04.3

**Issue**:

I have a problem with connection the FB Messenger. I have included pull request #160 and also tried it with the old dependency pymessenger and with my workaround here  is supposed in Bug #153 

I get the **errormessage**:

```
2018-01-08 12:13:06 WARNING  rasa_core.channels.facebook - Invalid fb verify token! Make sure this matches your webhook settings on the facebook app.
127.0.0.1 - - [2018-01-08 12:13:06] "GET /webhook?hub.mode=subscribe&hub.challenge=246570936&hub.verify_token=my-rasa-testbot HTTP/1.0" 200 157 0.001802
2465709362018-01-08 
```
if i run

```
python -m rasa_core.run -d models/dialogue -u models/nlu/current    --port 5002 --connector facebook --credentials credentials.yml

```

and send a message (as an owner) to my Bot. 

The webhook looks like it is correctly installed:
![webhook](https://user-images.githubusercontent.com/7667003/34671199-e5ba5008-f479-11e7-9b2b-ef37866133b3.JPG)
I connect to my bot via an nginx proxy server with an Let's encrypt cert installed. 

In the `credentials.yml` I use the `secret ` from here. Is this correct?
![app secret](https://user-images.githubusercontent.com/7667003/34671241-14a1bdf2-f47a-11e7-9062-10708d9671c7.JPG)

What else can I try?

**Comment by tmbo** [comment]
When creating these events, you entered a verify token on the facebook page, is it same as the one you added to the credentials? (remember, rasa doesn't complain about the secret, but about the verification token)

**Comment by bastiW** [comment]
In the credetnials.yml I have 
`verify: "my-rasa-bot"
`

and on facebook I have this

![verify token](https://user-images.githubusercontent.com/7667003/34672325-4a3414e8-f47e-11e7-8e26-20beeb26a539.JPG)

Then i click verify and save

and get the following output on the console

```
127.0.0.1 - - [2018-01-08 13:18:08] "GET /webhook?hub.mode=subscribe&hub.challenge=1149196825&hub.verify_token=my-rasa-bot HTTP/1.0" 200 145 0.001333

```



> (remember, rasa doesn't complain about the secret, but about the verification token)

It seems like the verification token process is working as expected. Only get the `Invalid fb verify token! Make sure this matches your webhook settings on the facebook app.` if I send a message to the bot.

**Comment by tmbo** [comment]
Mhm that sounds strange. I just tested it again with the moodbot example. Maybe there is something going wrong that is specific to python3. I'll give it a try with that as well.

**Comment by ladak** [comment]
I have the exact same problem...

**Comment by ladak** [comment]
Using Cygwin in Windows 10
Anaconda with Python 3.6
Rasa latest master version.

**Comment by tmbo** [comment]
Keep in mind that the moodbot sample doesn't ship with valid credentials! So you need to create your own facebook page and create your credentials on the developers page.

@ladak did you create your own credentials?

**Comment by ladak** [comment]
@tmbo - This is on my own app.

**Comment by ladak** [comment]
@tmbo - Extract of my code.

def run(serve_forever=True):
    interpreter = RasaNLUInterpreter("models/nlu/current")
    agent = Agent.load("models/dialogue", interpreter=interpreter)
    
    #FACEBOOK connection parameters

    fb_verify='thisisatestbotevahelps'  # you need tell facebook this token, to confirm your URL
    fb_secret='my facebook secret'  # your app secret
    FB_PAGE_ACCESS_TOKEN='my facebook access token'
    FB_PAGE_ID='428768704206301'
        
    input_channel = FacebookInput(
        fb_verify,
        fb_secret,
        fb_tokens={FB_PAGE_ID: FB_PAGE_ACCESS_TOKEN},   # page ids + tokens you subscribed to
        debug_mode=True    # enable debug mode for underlying fb library
    )

    if serve_forever:
        #agent.handle_channel(ConsoleInputChannel())
        agent.handle_channel(HttpInputChannel(5004, "/app", input_channel))
    return agent

**Comment by tmbo** [comment]
But that is different - you are using the version from pip right? The author of this issue used the master version from the repository which uses a new version of the facebook connector

**Comment by ladak** [comment]
I am using a version installed by pip

**Comment by bastiW** [comment]
>  Maybe there is something going wrong that is specific to python3.

YES. Thats seems to be the right path. 
Just tested with Python 2.7.14 |Anaconda custom (64-bit)| 

and it works.

**Comment by bastiW** [comment]
@ladak There were some changes recently. https://github.com/RasaHQ/rasa_core/pull/160 Those were already merged into master branch

**Comment by tmbo** [comment]
should be fixed in the latest master version - there was an encoding issue with py3 and hmac.

**Comment by bastiW** [comment]
Yes Thank you. It is working now.

**Comment by SibaprasadM** [comment]
I am still facing the same issue in python 3.5.4 Anaconda.
Moreover I am not able to test it with python 2.7 as I am not able to install tensorflow in python 2.7
I am using ngrok to redirect page messages to localhost.
Using Endpoint similar to : https://436d4633.ngrok.io/app/webhook

![image](https://user-images.githubusercontent.com/28738384/36770733-fd6cb07c-1c71-11e8-94b7-765f79d6118d.png)
