### ISSUE TITLE
ConsoleInputChannel is Gone

### ISSUE THREAD

**Issue by adrianhumphrey111** [RasaHQ/rasa_core#899]
**Rasa Core version**: Current Github Master

**Python version**: Python3.6

**Operating system** (windows, osx, ...): osx

**Issue**: The ConsoleInputChannel is no longer in channels.console. It breaks on my local machine and it also breaks inside of the Quick Start on the Documents page.

![image](https://user-images.githubusercontent.com/16964539/44634925-5f899800-a954-11e8-8189-7bb2f0b01a92.png)

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by amn41** [comment]
thanks for pointing this out! this hadn't updated to the newest version. on it!

**Comment by akelad** [comment]
The updated version of the docs should work now. For getting it to work on your local machine, please refer to the migration guide: http://rasa.com/docs/core/master/migrations/

**Comment by adrianhumphrey111** [comment]
Sorry, It still does not work. Also, you pointed me to the migration guide, however, I still do not know where to find the ConsoleInputChannel. Where do I import it from? Can I import it? Do I need to create my own Custom InputChannel, because it seems you are still using this in the docs, and it is still broken.

**Comment by akelad** [comment]
Please take a look at the run script on how to run it on the command line: https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/run.py#L275
